services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "81:80"
      - "82:443"
      - "5433:5432"
      # - "443:443"
    env_file:
      - env
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./ssl:/usr/local/etc/haproxy/ssl:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
