services:
  haproxy:
    image: haproxy:lts
    container_name: haproxy
    ports:
      - "80:80"
      - "443:443"
      - "5432:5432"
    env_file:
      - env
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./ssl:/usr/local/etc/haproxy/ssl:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
